channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=24.0
- pip:
  - mlflow==2.13.0
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - packaging==21.3
  - psutil==5.9.8
  - pyyaml==6.0
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
name: mlflow-env
